---
layout: cv
title: Youdh Abraham Manti's CV
---
# Youdh Abraham Manti
Finance Major, Business Analytics Minor.

<div id="webaddress">
<a href="mailto:abr22002@byui.edu">abr22002@byui.edu</a>
| <a href="https://www.linkedin.com/in/youdhabrahammanti/">My LinkedIn Profile</a>
| (385) 354-9044
</div>


## Currently

Seeking opportunities in Data Analytics and Finance.

### Specialized in

Financial Statements, Basic Accounting Principles, Data Verification.

### Research interests

Data Analytics, Financial Dashboards, Process Automation, Auditing.

## Education

`February 2023 - March 2026`
__Brigham Young University - Idaho__, Rexburg, Idaho
- BS Finance, Minor in Business Analytics
- Awarded Academic Grant


## Skills

* **Data Analytics:** Financial Statements, Basic Accounting Principles
* **Tools:** Excel (Pivot Tables, VBA, Macros), Power BI, Python, SQL
* **Languages:** English (Fluent), Hindi (Fluent), Telugu (Native), Tamil (Proficient)

## Experience

`August 2025 - September 2025`
__M/s UJJINENI & CO, Chartered Accountants__, Hyderabad, India
- **Audit Assistant**
- Returned for a second tenure due to high-quality deliverables.
- Executed complex data verification for financial audits using advanced Excel functions (VLOOKUP, Pivot Tables).
- Ensured 100% accuracy in client financial reporting.

`August 2024 - January 2025`
__Brigham Young University - Idaho__, Rexburg, Idaho
- **BA-215 Excel Spreadsheet TA**
- Guided 30+ students on advanced Excel functions (Pivot Tables, VBA, IF functions, advanced charts).
- Improved Excel proficiency by 10% among students through detailed feedback on 300+ projects.

## Certifications

`July 2025`
SQL Associate, *Data Camp*

`April 2025`
Business Administration, *BYU-Idaho*